Block spacing updates
WPMedia/news-theme-css pull request #51
Opened 2020-12-21 22:48 UTC by visionbegin

## Description
This ticket represents the design changes Brandon requested in his PR:  https://github.com/WPMedia/news-theme-css/pull/46.  However, I have kept old classes and mixins but deprecating them. Documentation has been updated as well that included if an entity has been deprecated.

## Jira Ticket
- https://arcpublishing.atlassian.net/browse/PEN-1475

## Acceptance Criteria
@brandonhunty will need to verify.  Right now there will be an associated PR for fusion-news-theme-blocks however I am unable to push it as there is an issue with the test library.

## Review Checklist
_The author of the PR should fill out the following sections to ensure this PR is ready for review._
- [x ] Confirmed all the test steps above are working
- [x ] Confirmed there are no linter errors
- [x ] Confirmed this PR has reasonable code coverage
  - [x ] Confirmed this PR has unit test files
  - [x ] Ran `npm test`, made sure all tests are passing
  - [ ] If the amount of work to write unit tests for this change are excessive,
please explain why (so that we can fix it whenever it gets refactored).
- [ x] Confirmed relevant documentation has been updated/added.

2020-12-24 16:18 UTC, RobinGiannattasio approved these changes
The code looks good to me!

2020-12-28 12:26 UTC, JackHowa commented
yo Brent! when you're up, check out https://github.com/WPMedia/fusion-news-theme-blocks/pull/643. I looked into the test issues. if that's ok, we can merge my branch. I reverted some of the package updates as well

2020-12-28 12:27 UTC, JackHowa requested changes
Not sure I totally understand the package-lock issues, may need to look into this fix more. but I have a working version of your branch with test instructions as well. hope you don't get this notification too early ;)

2020-12-28 12:29 UTC, JackHowa reviewed
oops commented on the wrong pr heh

2020-12-28 12:29 UTC, JackHowa approved these changes
looks good

2021-01-07 20:10 UTC, merged